### ISSUE TITLE
Suggestions for user action (shortcuts)

### ISSUE THREAD

**Issue by AndyK70** [PromGames/Coursedrawer#13]
When scrolling the mousewheel while hovering over the map, I'd like to have the zoom function set to it.

When selected the Zoom tool and dragging a rectangle it should be the portion to zoom.

Giving buttons keystroke-events (shortcuts):
i.e. Nodes: new, insert, deleting would like to have them on a key, as I would'nt continiously have to move the mousecursor back and forth between the toolbar and the nodes

Same to the mode buttons. Would like to have shortcuts to switch between modes.
Inserting a new node, dragging it a bit, then have to drag the map, then again the node...

**Comment by AndyK70** [comment]
closed... already implemented?

guys I can understand you would like to have a brief list of issues/suggestions/enhancements, but if an issue is not fixed/implemented/discarded please don't close it.
Set according label (postponed, etc.) and close it when it's done. Please.

Otherwise you and the submitter (me, in that case) can't follow your progress and development.

**Comment by PromGames** [comment]
Hi Andy,

Many of the issues proposed are really enhancement of the program and not bugs or malfunctions. We would like to publish this tool as son as possible and that's why we would like to keep the issues with mainly bugs and malfunctions reported active.

You can access our pivotal tracker where you can see the progress of our work and all you proposals reflected in task list format.

Trying to do this In GitHub, at issue level is going to be difficult, and is why I just close those issues and postponed to the next release.

I appreciate your understanding

**Comment by AndyK70** [comment]
Well, an issue is not just a bug or a problem.
An issue is something to care about. This can be a bug or a problem, it can be sth. do to for a future release, too. Therefor GitHub has those labels suggestion, enhancement, ToDo, postponed, etc. and they are different than the labels bug or problem.

But of course it's your decision how to handle it.

**Comment by PromGames** [comment]
Hi Andy,

I have just condensed all enhancement issues in one post to have follow up. You were totally right.

You can find the pivotal Tracker in this url:  https://www.pivotaltracker.com/n/workspaces/526046
I can provide you access and we will be very happy that you can participate with us in this project. For that I need your email or account in Pivotal Tracker. You can send to me by PM, is public in my profile.
