### ISSUE TITLE
IDs of courses in courseplay change when saving with CD

### ISSUE THREAD

**Issue by AndyK70** [PromGames/Coursedrawer#19]
If got the problem, that CD is enumerating the course IDs over.

When I leave FS15 to edit on a course I leave the courses attached to the cars.
Then I edit with CD, save it and relaunch LS15.
If there were courses I put in the trash bin, before editing there is a gap in the IDs.
CD now has closed the gap recounting the IDs and and saved the courseplay.xml with the new counting.
In the vehicles.xml is a courseplay tag attached to the corresponding vehicle tag and in that cp tag is the attribute courses, where the IDs are stored which are attached to that vehicle.

If CD changes the IDs by recounting them, it's all getting a mess.
My combines go wild, because they are not having their field courses anymore, but a transport course, or a mowing course, or whatever. and so on.

Not very good, I have to check every single vehicle if the courses are still they should be...

Please let the IDs of the courses untouched, even if there are gaps in the counting.

**Comment by PromGames** [comment]
Hi Andy,

 

You are right, the system is doing a renumbering of Id’s every single time you create or delete a course. This is coming from the original author and we didn’t touch it.

 

We will see what is the effect of not re-indexing the courses. Thnx for the info.

 

De: AndyK70 [mailto:notifications@github.com] 
Enviado el: jueves, 15 de enero de 2015 8:06
Para: PromGames/Coursedrawer
Asunto: [Coursedrawer] IDs of courses in courseplay change when saving with CD (#19)

 

If got the problem, that CD is enumerating the course IDs over.

When I leave FS15 to edit on a course I leave the courses attached to the cars.
Then I edit with CD, save it and relaunch LS15.
If there were courses I put in the trash bin, before editing there is a gap in the IDs.
CD now has closed the gap recounting the IDs and and saved the courseplay.xml with the new counting.
In the vehicles.xml is a courseplay tag attached to the corresponding vehicle tag and in that cp tag is the attribute courses, where the IDs are stored which are attached to that vehicle.

If CD changes the IDs by recounting them, it's all getting a mess.
My combines go wild, because they are not having their field courses anymore, but a transport course, or a mowing course, or whatever. and so on.

Not very good, I have to check every single vehicle if the courses are still they should be...

Please let the IDs of the courses untouched, even if there are gaps in the counting.

**Comment by Madbros** [comment]
mhh, can be tricky, because I think a lot of code is index based... let me some time

**Comment by AndyK70** [comment]
Would suggest to include the course ID as extra entry, so you can leave the enumeration as is.
You just have to change the write to disk function, that not the enumerated ID is written, but the saved entry of the course ID.
